### ISSUE TITLE
String Parser

### ISSUE THREAD

**Issue by spy16** [enescakir/emoji#3]
Not sure if this is project goal or not. But I think a string parser that takes a string (for example `I am cool :sunglasses: ` ) and returns a string that has `:sunglasses:`  replaced with the actual emoji character would be really useful. 

Most uses cases I can think of would not involve manipulating specific emojis in code. Even if it did,  defining specific emoji characters required  by the project as constants in the project instead of introducing a dependency would be simpler and easier. In that sense, above feature can add great value to this project I think .   

If you think this would be useful, I can send a PR.

**Comment by enescakir** [comment]
Hi @spy16, thanks for the suggestion 😊

I have a to-do item on README for this feature.
> Add emoji string replacer
But I think string parser is more descriptive than replacer.

I already start to develop it.

When I create PR, I am gonna ask review from you.

**Comment by spy16** [comment]
Oh great! Didn't notice that.

**Comment by spy16** [comment]
> When I create PR, I am gonna ask review from you.

Sure :+1:

Nice library by the way.

**Comment by enescakir** [comment]
Hi @spy16,
I created PR #4 for this feature. Basic stuff is done. I am writing tests for it now 🚀 
It has `emoji.Parse(str string) string` for replacing emoji aliases.
Also, it has `Sprint`, `Sprintf`, `Printf` etc. for wrapping `fmt` library.

I added emoji aliases from [github/gemoji](https://github.com/github/gemoji) in addition to unicode list. Because unicode list doesn't have all GitHub emoji aliases.

Can you review it? 😌 
Generator code gone little bit messy, I am going to clean it in the future. 🤖 
You can focus public part of the this feature, not `internal` package 😀

**Comment by spy16** [comment]
Sorry have been busy, couldn't get back to you. But i like the `fmt` interfafce and the changes look fine. It should be okay to close this issue.
